replicaCount: 1
image:
  tag: latest
  pullPolicy: IfNotPresent
  version: latest

ingress:
  enabled: true


readinessProbe:
  path: /actuator/health
  initialDelay: 30
  period: 10

livenessProbe:
  path: /actuator/health
  initialDelay: 45
  period: 15

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi


