replicaCount: 1

image:
  tag: latest
  version: latest
  pullPolicy: IfNotPresent

global:
  probes:
    readiness:
      path: /actuator/health
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      path: /actuator/health
      initialDelaySeconds: 45
      periodSeconds: 15
      failureThreshold: 3
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 1024Mi

api-gateway:
  image:
    repository: api-gateway
  service:
    port: 8080

auth-service:
  image:
    repository: auth-service
  service:
    port: 8080

inventory-service:
  image:
    repository: inventory-service
  service:
    port: 8080

notification-service:
  image:
    repository: notification-service
  service:
    port: 8080

order-service:
  image:
    repository: order-service
  service:
    port: 8080

product-service:
  image:
    repository: product-service
  service:
    port: 8080

user-service:
  image:
    repository: user-service
  service:
    port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: api-gateway.local
      paths:
        - path: /
          pathType: Prefix