replicaCount: 1
image:
  tag: latest
  pullPolicy: IfNotPresent
  version: latest

ingress:
  enabled: true

resources:
  limits:
    cpu: "200m"
    memory: "500Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"


