replicaCount: 1
image:
  tag: latest
  pullPolicy: IfNotPresent
  version: latest

ingress:
  enabled: true

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"


