apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-gateway-deployment-{{.Values.image.version}}"
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "api-gateway:{{.Values.image.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
        - livenessProbe:
           httpGet:
            path: {{ .Values.global.probes.liveness.path }}
            port: 8081
           initialDelaySeconds: {{ .Values.global.probes.liveness.initialDelaySeconds }}
           periodSeconds: {{ .Values.global.probes.liveness.periodSeconds }}
        - readinessProbe:
           httpGet:
            path: {{ .Values.global.probes.readiness.path }}
            port: 8081
           initialDelaySeconds: {{ .Values.global.probes.readiness.initialDelaySeconds }}
           periodSeconds: {{ .Values.global.probes.readiness.periodSeconds }}
