apiVersion: apps/v1
kind: Deployment
metadata:
  name: "notification-service-deployment-{{.Values.image.version}}"
  labels:
    app: notification-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: "notification-service:{{.Values.image.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8084