apiVersion: apps/v1
kind: Deployment
metadata:
  name: "product-service-deployment-{{.Values.image.version}}"
  labels:
    app: product-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: "product-service:{{.Values.image.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8086
        - livenessProbe:
            httpGet:
              path: {{ .Values.global.probes.liveness.path }}
              port: 8086
            initialDelaySeconds: {{ .Values.global.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.probes.liveness.periodSeconds }}

        - readinessProbe:
            httpGet:
              path: {{ .Values.global.probes.readiness.path }}
              port: 8086
            initialDelaySeconds: {{ .Values.global.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.probes.readiness.periodSeconds }}