apiVersion: apps/v1
kind: Deployment
metadata:
  name: "user-service-deployment-{{.Values.image.version}}"
  labels:
    app: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: "user-service:{{.Values.image.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8087
        - livenessProbe:
            httpGet:
              path: {{ .Values.global.probes.liveness.path }}
              port: 8087
            initialDelaySeconds: {{ .Values.global.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.probes.liveness.periodSeconds }}
        - readinessProbe:
            httpGet:
              path: {{ .Values.global.probes.readiness.path }}
              port: 8087
            initialDelaySeconds: {{ .Values.global.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.probes.readiness.periodSeconds }}