name: Build and Push Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          export VERSION=$(date +%Y%m%d)-$(git rev-parse --short HEAD)
          for SERVICE in api-gateway auth-service inventory-service notification-service order-service product-service  user-service; do
            docker build -t $SERVICE:$VERSION -f $SERVICE/Dockerfile .
            docker tag $SERVICE:$VECTION ${{ secrets.DOCKER_HUB_USERNAME }}/$SERVICE:$VERSION
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$SERVICE:$VERSION
          done
