name: Build and Push Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests
          for SERVICE in api-gateway auth-service inventory-service notification-service order-service product-service user-service; do
            mkdir -p $SERVICE/target/docker
            cp $SERVICE/target/*.jar $SERVICE/target/docker/
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker images
        run: |
          export VERSION=$(date +%Y%m%d)-$(git rev-parse --short HEAD)
          for SERVICE in api-gateway auth-service inventory-service notification-service order-service product-service user-service; do
            docker build -t $SERVICE:$VERSION -f $SERVICE/Dockerfile $SERVICE
            docker tag $SERVICE:$VERSION ${{ secrets.DOCKER_HUB_USERNAME }}/$SERVICE:$VERSION
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$SERVICE:$VERSION
          done
