name: Full Pipeline

on:
  push:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Start k3d
        run: |
          k3d cluster create ci --port "8080:30080@loadbalancer"
          kubectl cluster-info

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          helm upgrade --install app ./helm-chart \
            --set image.tag=$GITHUB_SHA
          
          kubectl wait --for=condition=available deployment/app --timeout=90s
