name: Full Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          sudo apt-get update && sudo apt-get install -y kubectl
          
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Start k3d cluster
        run: |
          k3d cluster create ci \
            --port "8080:30080@loadbalancer" \
            --wait

          mkdir -p ~/.kube
          k3d kubeconfig get ci > ~/.kube/config
          kubectl cluster-info

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Helm
        run: |
          # Установка Helm (если не установлен)
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          
          mkdir -p ~/.kube
          k3d kubeconfig get ci > ~/.kube/config

      - name: Deploy application
        run: |
          cd helm-chart || { echo "Directory helm-chart not found"; exit 1; }
          
          helm upgrade --install app . \
            --namespace default \
            --create-namespace \
            --set image.tag=$GITHUB_SHA \
            --atomic \
            --timeout 5m
          
          kubectl wait --for=condition=available deployment/app --timeout=120s

      - name: Verify deployment
        run: |
          kubectl get pods -o wide
          kubectl get svc
          helm list
