name: Full Pipeline

on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install k3d and tools
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash
          echo "::add-path::/home/runner/bin"  # Добавляем путь к k3d
          k3d version
          
          sudo apt-get update && sudo apt-get install -y kubectl
          curl -sSfL https://get.helm.sh/helm-v3.18.3-linux-amd64.tar.gz | tar xz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version

      - name: Create k3d cluster
        run: |
          k3d cluster create ci \
            --port "8080:30080@loadbalancer" \
            --wait
          
          mkdir -p ~/.kube
          k3d kubeconfig get ci > ~/.kube/config
          kubectl cluster-info

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure access
        run: |
          mkdir -p ~/.kube
          k3d kubeconfig get ci > ~/.kube/config
          kubectl get nodes

      - name: Deploy with Helm
        run: |
          cd helm-chart || exit 1
          helm upgrade --install app . \
            --set image.tag=$GITHUB_SHA \
            --atomic \
            --timeout 5m
          
          kubectl wait --for=condition=available deployment/app --timeout=120s

      - name: Verify
        run: |
          kubectl get pods,svc
          helm list
