name: PR Checks

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run unit tests with coverage
        run: |
          ./mvn clean test jacoco:report
          ./mvn jacoco:check

      - name: Checkstyle
        run: ./mvn checkstyle:check
