name: PR Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with coverage
        run: |
          chmod +x mvnw
          ./mvnw clean verify
          
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            **/target/site/jacoco
            **/target/site/jacoco-aggregate

      - name: Checkstyle
        run: ./mvnw checkstyle:check

      - name: Show test failures
        if: failure()
        run: |
         cat auth-service/target/surefire-reports/*.txt
         cat auth-service/target/surefire-reports/*.xml
