name: PR Checks

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run unit tests with coverage
        run: |
          chmod +x mvnw
          ./mvnw clean verify -e -X
          ./mvnw jacoco:check -e -X
          ./mvnw jacoco:report -e -X

      - name: Checkstyle
        run: ./mvnw checkstyle:check
